# src/Blogger/BlogBundle/Resources/config/index.yml
BloggerBlogBundle_homepage:
    pattern:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        _method:  GET

# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_about:
    pattern:  /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        _method:  GET

# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_contact:
    pattern:  /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
        _method:  GET|POST

BloggerBlogBundle_search:
    pattern:  /search
    defaults: { _controller: BloggerBlogBundle:Search:index }
    requirements:
        _method:  GET|POST

BloggerBlogBundle_find:
    pattern:  /search/{id}
    defaults: { _controller: BloggerBlogBundle:Search:find }
    requirements:
        _method:  GET
